### ISSUE TITLE
いいところ診断に「優しさ」を追加されてはいかがでしょうか？

### ISSUE THREAD

**Issue by upaukapaua** [steakasanjurou/assessment#1]
いいところ診断に「優しさ」を追加されてはいかがでしょうか？
内容は

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

というものです。

**Comment by steakasanjurou** [comment]
ありがとうございます。
診断結果をもっと増やしたいとと考えていたところなので、とてもありがたいです。
「優しさ」の結果をその文言どおり追加しますね。

**Comment by upaukapaua** [comment]
私の愚案を採用していただきありがとうございます。

**Comment by steakasanjurou** [comment]
仕上がりました。
診断したい名前を「e」にすると「優しさ」の結果が出ます。

**Comment by upaukapaua** [comment]
ありがとうございます。
これでこのイシューを仕舞います。
